# Function - one-hot encoding

In [1]:
import numpy as np

## Definir entradas e saídas para os testes

In [2]:
# inputs
aa = np.array([2,0,3,2,1])
print(aa)

[2 0 3 2 1]


In [3]:
# outputs
oo = np.array([[0,0,1,0],
               [1,0,0,0],
               [0,0,0,1],
               [0,0,1,0],
               [0,1,0,0]])
print(oo)

[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


## Adiciona os testes (Código do professor)

In [4]:
from jn_tester.professor.models import TestCase, TestSet

def equal(x, y):
   return 1.0 if np.sum(x - y)==0 else 0.0

# Outros testes podem ser adicionados
bb = np.array([1,1,3,2,4])

oo2 = np.array([[ 0,  1,  0,  0,  0],
                [ 0,  1,  0,  0,  0],
                [ 0,  0,  0,  1,  0],
                [ 0,  0,  1,  0,  0],
                [ 0,  0,  0,  0,  1]])

# Adiciona test cases
test = TestSet()
test.add_new_test_case(TestCase(aa, oo, assert_function=equal))
test.add_new_test_case(TestCase(bb, oo2, assert_function=equal))

# O arquivo criado 'one_hot.test' deverá ser disponibilizado aos alunos
test.save('one_hot')

In [5]:
print(test.test_cases)

[<jn_tester.professor.models.TestCase object at 0x7f792c0e4160>, <jn_tester.professor.models.TestCase object at 0x7f792c0e09b0>]


## Código do Aluno

In [6]:
# Try to avoid explicit loop as much as possible
# Use only NumPy operations, no other libraries
def one_hot(i):
    return np.eye(np.max(i)+1)[i]

print(one_hot(aa))


[[ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]]


In [7]:
# test
from jn_tester.student.test import run_test, submit_test

print(run_test('one_hot', fnc=one_hot))
# or
submit_test('one_hot', fnc=one_hot, presentation_mode='table')  # envio do código


Showing results: one_hot
--------------------
Final score:  100%
1 :  [1.0/1.0] => OK
 - time:  0.061472  ms
 - memory:  90.54  Mb
2 :  [1.0/1.0] => OK
 - time:  0.094171  ms
 - memory:  90.55  Mb
None

Showing results: one_hot
--------------------
Final score:  100%


Score         Time    Memory
Test 1  100%    0.0685 ms  90.56 Mb
Test 2  100%  0.179412 ms  90.56 Mb

## Código do Professor - Visualização dos resultados

In [8]:
from jn_tester.professor.tables import view_complete_table

view_complete_table('one_hot', base_path='/home/**/')   # Neste caso a pasta home sera escaneada inteira para encontrar os resultados.